### Add user
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "name": "Dowon Lee",
  "email": "edowon0623@gmailc.om",
  "pwd": "12345678"
}
###

### Login user
POST http://localhost:8000/user-service/login
Content-Type: application/json

{
  "email": "edowon0623@gmailc.om",
  "password": "12345678"
}
###

GET http://localhost:8000/user-service/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjZWQ5OWI0NC1jYzdlLTQ1YjktYjlkOC1mNjg2ODNjZjAxMDgiLCJleHAiOjE3MjQ3NjEyNzEsImlhdCI6MTcyNDY3NDg3MX0.O8RIxfmEmwJl5L_0HA-ad_suCuBmCPZ1_qRwStohPpEkSyEux6DcucihE3NO3z7WDbov_t6RxLS0yOjQOUqwuw
