# Use root/example as user/password credentials
version: '3.1'

services:
  user-service:
    image: user-service:1.0

    environment:
      spring.cloud.config.uri: http://config-service:8888
      spring.rabbitmq.host: rabbitmq
      spring.zipkin.base-url: http://zipkin-zipkin-1:9411
      eureka.client.service-url.defaultZone: http://service-discovery:8761/eureka/
      management.zipkin.tracing.endpoint: http://zipkin-zipkin-1:9411/api/v2/spans
    networks:
      my-network:

networks:
  my-network:
    external: true
    name: ecommerce-network
